name: test
on:
  push:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install-node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: install-pnpm
        uses: pnpm/action-setup@v4

      - run: pnpm i
      - name: test
        run: npm run test
      - name: coverage
        run: npm run coverage
      # - name: Coveralls
      #   uses: coverallsapp/github-action@v2
